apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  schedule: {{ .Values.schedule }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ .Chart.Name }}
        spec:
          restartPolicy: {{ .Values.restartPolicy }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                - unseal
                - --address={{ required "A address is required for Vault Server" .Values.vault.address }}
                {{- range .Values.vault.shards }}
                - --shard={{ required "A Shard (unseal key) is required" . }}
                {{- end }}
                {{- range $k, $v := .Values.vault.customHeaders }}
                - --custom-header={{ $k }}={{ $v }}
                {{- end }}
